export const INITIAL_ACTION = "INITIAL_ACTION";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const API_CALL_IN_ACTION = "API_CALL_IN_ACTION";
export const ON_INPUT_CHANGE = "ON_INPUT_CHANGE";
export const INPUT_ERROR = "INPUT_ERROR";
export const SUBMISSIONS_SUCCESS = "SUBMISSIONS_SUCCESS";
export const CLEAR_SUBMISSIONS_RESPONSE = "CLEAR_SUBMISSIONS_RESPONSE";
